spring:
  application:
    name: GATEWAY-SERVICE
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health, info

hystrix:
  command:
    fallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
