server:
  port: 9292

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment-microservice
    username: root
    password: root

  application:
    name: PAYMENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev